## Data Analytics using NumPy 

In [1]:
import numpy as np

In [2]:
# 1.Create a rank 2 numpy array of random integers and print:
# a) shape,size and dimensions of the array 
# b) number of odd and even integers in the array

arr = np.random.randint(5,size=(2,3))                
print("arr=")
print(arr)

print("\narr shape=")
print(arr.shape)

print("\narr size=")
print(arr.size)


print("\narr dim=")
print(arr.ndim)

even = arr[arr%2 == 0]
print("\neven no count=")
print(even.size)

even = arr[arr%2 != 0]
print("\nodd no count=")
print(even.size)


arr=
[[4 2 2]
 [4 1 4]]

arr shape=
(2, 3)

arr size=
6

arr dim=
2

even no count=
5

odd no count=
1


In [3]:
# 2.Create a (3X3) numpy array with values ranging from 1 to 9.

arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 3.Create a (5X5) random numpy array and print the numbers from the array which are greater than average value of the array.
# Hint: Use np.where() function

arr_new = np.random.randint(9,size=(5,5))
print(arr_new)

avg = arr_new.mean()
print("average = "+str(avg))

print("\nnumber greater than avg = ")
print(arr_new[np.where(arr_new>avg)])

[[0 3 6 6 1]
 [4 5 8 1 7]
 [8 5 0 0 5]
 [5 8 3 8 6]
 [6 2 0 6 7]]
average = 4.4

number greater than avg = 
[6 6 5 8 7 8 5 5 5 8 8 6 6 6 7]


In [5]:
# 4.Given an array of random integers:
arr1 = np.random.randint(50,size=(10,10))
# Find out : a) row wise and column wise mean b) row wise and column wise max and min values c) Variance and Standard Deviation 
# of the array.
print(arr1)
print("\nrow wise mean")
print(arr1.mean(axis = 1))

print("\ncolumn wise mean")
print(arr1.mean(axis = 0))

print("\nrow wise max")
print(arr1.max(axis = 1))

print("\nrow wise min")
print(arr1.min(axis=1))

print("\ncol wise max")
print(arr1.max(axis = 0))

print("\ncol wise min")
print(arr1.min(axis=0))


print("\nrow wise std")
print(arr1.std(axis = 1))

print("\nrow wise var")
print(arr1.var(axis=1))

print("\ncol wise std")
print(arr1.std(axis = 0))

print("\ncol wise var")
print(arr1.var(axis=0))





[[27 26 29  2 38  0 41 30 18 45]
 [ 6 25 36 46 36 15  1 33 46 43]
 [ 4  1 35 33  5 39  9 28 10 44]
 [ 0 15 13  5 40 11 12 21 36 47]
 [48 28 12  3 39 44 17 20 32  8]
 [21 37 47 32 15 33  8 46 13 46]
 [18 41  1 44 49  4 42 29 11 35]
 [39 35 14 49 30 20 31 24 26 44]
 [37 43 35  2 22 34 43  7 46 35]
 [ 0 28 39 42 23 11  7 31 27 14]]

row wise mean
[25.6 28.7 20.8 20.  25.1 29.8 27.4 31.2 30.4 22.2]

column wise mean
[20.  27.9 26.1 25.8 29.7 21.1 21.1 26.9 26.5 36.1]

row wise max
[45 46 44 47 48 47 49 49 46 42]

row wise min
[ 0  1  1  0  3  8  1 14  2  0]

col wise max
[48 43 47 49 49 44 43 46 46 47]

col wise min
[ 0  1  1  2  5  0  1  7 10  8]

row wise std
[14.3888846  15.53093687 15.65758602 14.93318452 14.74754217 13.93413076
 16.74037037 10.28396811 14.4374513  13.1362095 ]

row wise var
[207.04 241.21 245.16 223.   217.49 194.16 280.24 105.76 208.44 172.56]

col wise std
[16.55294536 11.97873115 14.19471733 19.27589168 12.66530694 14.60445138
 15.59134375  9.59635347 12.83939251 1

In [6]:
# 5.Given two matrices:
arr1 = np.matrix([[4,5],[7,3]])
arr2 = np.matrix([[2,3],[8,9]])

# Find out the matrix multiplication of the above two matrices without using numpy function and then verify your answer 
# using np.dot(arr1,arr2) function


multiplication = np.matrix([[0,0],[0,0]])
summ = 0
for i in range(0,2):
    for j in range(0,2):
        for k in range(0,2):
            multiplication[i,j]= multiplication[i,j]+arr1[i,k]*arr2[k,j]
print(multiplication)

print("\n")
print(np.dot(arr1,arr2))

[[48 57]
 [38 48]]


[[48 57]
 [38 48]]
